Proxy
galiosmax/networkLabs pull request #1
Opened 2018-12-30 22:36 UTC by galiosmax

2018-12-31 06:24 UTC, Aloomenon requested changes
Оставил несколько замечаний по коду.
Каждое из замечаний обсуждается и не обязательно к исправлению, если сможете меня в этом убедить.
Закрывать обсуждения по каждому из случаев не надо, я сделаю это сам.

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +    class Client {
Лучше уж создать еще 1 файл с классом, чем заливать 400+ строк

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +            server.start();
Ошибки везде прокидываются вплоть до main(String[]). У нас летит неправильные данные при подключении клиента, а валится сам прокси. Негоже так делать!

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +                byteBuffer.clear();
может все-таки заобузить try-catch ? Заодно решится проблема с прокидкой ошибок и очисткой ресурсов.

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +            if (client.isConnected()) {
мне кажется, что эта проверка и проверки ниже, должны быть до того, как заполняется connectionBuffer. Если уж валимся тут, то инициализация буфера и его заполнение было пустой тратой ресурсов и времени.

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +            printHelp();
Вот это круто! :+1:

2018-12-31 06:24 UTC, Aloomenon commented on Socks5/src/Socks.java
> +        selector = Selector.open();
Открыл, ок. А еще открыл serverSocketChannel и dnsChannel. А закрывать кто будет? Стоит учесть, что если летит Exception, то они никогда сами по себе не закроются.

2019-01-02 01:38 UTC, galiosmax commented on Socks5/src/Socks.java
> +    class Client {
@Aloomenon я починил

2019-01-02 05:21 UTC, Aloomenon requested changes

2019-01-02 05:21 UTC, Aloomenon commented on Socks5/src/Socks.java
> +                                } catch (NullPointerException e) {
Ловить unchecked exceptions - дурной тон. Лучше проверять на null те места, откуда может лететь.

2019-01-02 05:51 UTC, Aloomenon commented on Socks5/src/Socks.java
> +                                } catch (NullPointerException e) {
@galiosmax поправь это и посмотрим как работает.

2019-01-02 06:48 UTC, galiosmax commented on Socks5/src/Socks.java
> +                                } catch (NullPointerException e) {
@Aloomenon поправил, там просто летело, а я не очень понимал откуда

2019-01-02 07:35 UTC, Aloomenon commented
@galiosmax Принято! Можно вливать в мастер.

2019-01-02 07:37 UTC, merged